var listSubject = [
{id: 1, text: 'CHUM1' },
{id: 2, text: 'CHUM2' },
{id: 3, text: 'CHUS1' },
{id: 4, text: 'CHUS2' },
{id: 5, text: 'CHUS3' },
{id: 6, text: 'CINQ1' },
{id: 7, text: 'CINQ2' },
{id: 8, text: 'CINQ3' },
{id: 9, text: 'ISMD1' },
{id: 10, text: 'ISMD2' },
{id: 11, text: 'ISMD3' },
{id: 12, text: 'IUGM1' },
{id: 13, text: 'IUGM2' },
{id: 14, text: 'IUGM3' },
{id: 15, text: 'MNI1' },
{id: 16, text: 'MNI2' },
{id: 17, text: 'MNI25' },
{id: 18, text: 'MNI3' }
];
